import Head from 'next/head'
import Grid from '@components/Grid'
import TechCard from '@components/TechnologyCard'
import HeroSection from '@components/HeroSection'

export default function Home() {
	return (
		<>
			<Head>
				<title>App Makers</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/logo-96.png" />
			</Head>
			<HeroSection/>
			<Grid/>
			<TechCard/>
		</>
	)
}
